In [2]:
import numpy as np

In [3]:
import pandas as pd

In [5]:
data = pd.read_csv("D:/LetsUpgrade/day25/train.csv")

In [6]:
data.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0      1      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0      1      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  889 non-null    int64  
 1   Survived     889 non-null    int64  
 2   Pclass       889 non-null    int64  
 3   Sex          889 non-null    object 
 4   Age          889 non-null    float64
 5   SibSp        889 non-null    int64  
 6   Parch        889 non-null    int64  
 7   Fare         889 non-null    float64
 8   Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(2)
memory usage: 62.6+ KB


In [9]:
data.describe().T

count        mean         std   min       25%       50%    75%  \
PassengerId  889.0  446.000000  256.998173  1.00  224.0000  446.0000  668.0   
Survived     889.0    0.382452    0.486260  0.00    0.0000    0.0000    1.0   
Pclass       889.0    2.311586    0.834700  1.00    2.0000    3.0000    3.0   
Age          889.0   32.699854   14.346821  0.42   22.0000   32.0000   45.0   
SibSp        889.0    0.524184    1.103705  0.00    0.0000    0.0000    1.0   
Parch        889.0    0.382452    0.806761  0.00    0.0000    0.0000    0.0   
Fare         889.0   32.096681   49.697504  0.00    7.8958   14.4542   31.0   

                  max  
PassengerId  891.0000  
Survived       1.0000  
Pclass         3.0000  
Age           80.0000  
SibSp          8.0000  
Parch          6.0000  
Fare         512.3292

In [10]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Fare', 'Embarked'],
      dtype='object')

In [11]:
data.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [12]:
from sklearn import preprocessing

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
from sklearn.naive_bayes import GaussianNB

In [15]:
from sklearn.metrics import accuracy_score

In [16]:
from sklearn.metrics import confusion_matrix

In [17]:
le = preprocessing.LabelEncoder()

In [97]:
data["Sex"]=le.fit_transform(data["Sex"])

In [98]:
data["Embarked"]=le.fit_transform(data["Embarked"])

In [99]:
data.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1         0       3    1  22.0      1      0   7.2500         2
1            2         1       1    0  38.0      1      0  71.2833         0
2            3         1       3    0  26.0      0      0   7.9250         2
3            4         1       1    0  35.0      1      0  53.1000         2
4            5         0       3    1  35.0      0      0   8.0500         2

In [100]:
y = data["Survived"]

In [101]:
X = data.drop(["Survived","PassengerId"],axis=1)

In [102]:
y.count()

889

In [105]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [106]:
X_train.shape

(622, 7)

In [107]:
X_test.shape

(267, 7)

In [108]:
y_train.shape

(622,)

In [109]:
y_test.shape

(267,)

In [110]:
from sklearn.naive_bayes import *

In [111]:
clf = BernoulliNB()

In [112]:
y_pred = clf.fit(X_train,y_train).predict(X_test)

In [113]:
acc = accuracy_score(y_test,y_pred,normalize=True)
print( "accuracy = ",acc*100 ,"%")

accuracy =  77.15355805243446 %


In [114]:
confusion_matrix(y_test,y_pred)

array([[131,  26],
       [ 35,  75]], dtype=int64)

In [115]:
#Assignment

In [116]:
#Pclass

In [117]:
y = data["Pclass"]

In [118]:
X = data.drop(["Pclass","PassengerId"],axis=1)

In [119]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [120]:
X_train.shape

(622, 7)

In [121]:
X_test.shape

(267, 7)

In [122]:
y_train.shape

(622,)

In [123]:
y_test.shape

(267,)

In [124]:
X_train.head()

Survived  Sex   Age  SibSp  Parch     Fare  Embarked
350         0    1  45.0      0      0  35.0000         2
124         1    1  12.0      1      0  11.2417         0
577         0    0  45.0      1      0  14.4583         0
422         0    0  28.0      1      1  14.4000         2
118         0    0   2.0      4      2  31.2750         2

In [125]:
clf = BernoulliNB()

In [126]:
y_pred = clf.fit(X_train,y_train).predict(X_test)

In [127]:
acc = accuracy_score(y_test,y_pred,normalize=True)
print( "accuracy = ",acc*100 ,"%")

accuracy =  59.176029962546814 %


In [128]:
confusion_matrix(y_test,y_pred)

array([[ 30,   8,  32],
       [  9,  10,  30],
       [ 24,   6, 118]], dtype=int64)

In [129]:
#Sex

In [130]:
y = data["Sex"]

In [131]:
X = data.drop(["Sex","PassengerId"],axis=1)

In [132]:
X.head()

Survived  Pclass   Age  SibSp  Parch     Fare  Embarked
0         0       3  22.0      1      0   7.2500         2
1         1       1  38.0      1      0  71.2833         0
2         1       3  26.0      0      0   7.9250         2
3         1       1  35.0      1      0  53.1000         2
4         0       3  35.0      0      0   8.0500         2

In [133]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [134]:
clf = BernoulliNB()

In [135]:
y_pred = clf.fit(X_train,y_train).predict(X_test)

In [136]:
acc = accuracy_score(y_test,y_pred,normalize=True)
print( "accuracy = ",acc*100 ,"%")

accuracy =  74.53183520599251 %


In [137]:
confusion_matrix(y_test,y_pred)

array([[ 49,  49],
       [ 19, 150]], dtype=int64)

In [138]:
#Sibsp

In [139]:
y = data["SibSp"]

In [140]:
X = data.drop(["SibSp","PassengerId"],axis=1)

In [141]:
X.head()

Survived  Pclass  Sex   Age  Parch     Fare  Embarked
0         0       3    1  22.0      0   7.2500         2
1         1       1    0  38.0      0  71.2833         0
2         1       3    0  26.0      0   7.9250         2
3         1       1    0  35.0      0  53.1000         2
4         0       3    1  35.0      0   8.0500         2

In [142]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [143]:
clf = BernoulliNB()

In [144]:
y_pred = clf.fit(X_train,y_train).predict(X_test)

In [145]:
acc = accuracy_score(y_test,y_pred,normalize=True)
print( "accuracy = ",acc*100 ,"%")

accuracy =  68.91385767790263 %


In [146]:
confusion_matrix(y_test,y_pred)

array([[162,  20,   0,   0,   0,   0,   0],
       [ 43,  22,   0,   0,   0,   0,   0],
       [  6,   2,   0,   0,   0,   0,   0],
       [  5,   2,   0,   0,   0,   0,   0],
       [  2,   0,   0,   0,   0,   0,   0],
       [  1,   0,   0,   0,   0,   0,   0],
       [  2,   0,   0,   0,   0,   0,   0]], dtype=int64)

In [147]:
#Parch

In [148]:
y = data["Parch"]

In [149]:
X = data.drop(["Parch","PassengerId"],axis=1)

In [150]:
X.head()

Survived  Pclass  Sex   Age  SibSp     Fare  Embarked
0         0       3    1  22.0      1   7.2500         2
1         1       1    0  38.0      1  71.2833         0
2         1       3    0  26.0      0   7.9250         2
3         1       1    0  35.0      1  53.1000         2
4         0       3    1  35.0      0   8.0500         2

In [151]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [152]:
clf = BernoulliNB()

In [153]:
y_pred = clf.fit(X_train,y_train).predict(X_test)

In [154]:
acc = accuracy_score(y_test,y_pred,normalize=True)
print( "accuracy = ",acc*100 ,"%")

accuracy =  71.53558052434457 %


In [155]:
confusion_matrix(y_test,y_pred)

array([[182,  16,   0,   0,   0],
       [ 31,   9,   0,   0,   0],
       [ 24,   3,   0,   0,   0],
       [  1,   0,   0,   0,   0],
       [  1,   0,   0,   0,   0]], dtype=int64)

In [156]:
#Embarked

In [157]:
y = data["Embarked"]

In [158]:
X = data.drop(["Embarked","PassengerId"],axis=1)

In [159]:
X.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0         0       3    1  22.0      1      0   7.2500
1         1       1    0  38.0      1      0  71.2833
2         1       3    0  26.0      0      0   7.9250
3         1       1    0  35.0      1      0  53.1000
4         0       3    1  35.0      0      0   8.0500

In [160]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [161]:
clf = BernoulliNB()

In [162]:
y_pred = clf.fit(X_train,y_train).predict(X_test)

In [163]:
acc = accuracy_score(y_test,y_pred,normalize=True)
print( "accuracy = ",acc*100 ,"%")

accuracy =  73.40823970037454 %


In [164]:
confusion_matrix(y_test,y_pred)

array([[  0,   0,  49],
       [  0,   0,  22],
       [  0,   0, 196]], dtype=int64)